### ISSUE TITLE
WAR files can't be started

### ISSUE THREAD

**Issue by josephlewis42** [GoogleCloudPlatform/kf-buildpacks#5]
WAR files uploaded to the kf buildpacks fail to create an entrypoint and thus can't be started with the web type. The following message is displayed with a sample WAR:

```
Container failed with: Error: failed to launch: determine start command: process type web was not found
```

Example manifest:

```
applications:
- name: test
  instances: 1
  path: path/to/my/app.war  
```
